"""Scan an extracted project: filter noise, detect languages, frameworks and entry-point hints.

Pure filesystem reads. Produces a :class:`ScanResult` that later stages (code map, prompts,
estimate) consume. The scan never opens files bigger than ``max_file_bytes`` beyond a sniff.
"""

from __future__ import annotations

import json
import re
import tomllib
from collections import Counter
from collections.abc import Callable, Iterator
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

import pathspec
from pydantic import BaseModel, Field

Language = Literal[
    "python",
    "javascript",
    "typescript",
    "java",
    "go",
    "c",
    "cpp",
    "csharp",
    "ruby",
    "php",
    "rust",
    "text",
]

EXT_LANGUAGE: dict[str, Language] = {
    ".py": "python",
    ".pyi": "python",
    ".js": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".jsx": "javascript",
    ".ts": "typescript",
    ".mts": "typescript",
    ".cts": "typescript",
    ".tsx": "typescript",
    ".java": "java",
    ".go": "go",
    ".c": "c",
    ".h": "c",
    ".cc": "cpp",
    ".cpp": "cpp",
    ".cxx": "cpp",
    ".hpp": "cpp",
    ".hh": "cpp",
    ".hxx": "cpp",
    ".cs": "csharp",
    ".rb": "ruby",
    ".rake": "ruby",
    ".php": "php",
    ".rs": "rust",
}
TEXT_EXTS = {
    ".md",
    ".rst",
    ".txt",
    ".json",
    ".yaml",
    ".yml",
    ".toml",
    ".ini",
    ".cfg",
    ".env.example",
    ".sh",
    ".bash",
    ".zsh",
    ".sql",
    ".html",
    ".css",
    ".scss",
    ".vue",
    ".svelte",
    ".xml",
    ".gradle",
    ".kt",
    ".kts",
    ".swift",
    ".scala",
    ".dart",
    ".ex",
    ".exs",
    ".erl",
    ".hs",
    ".lua",
    ".pl",
    ".r",
    ".jl",
    ".proto",
    ".graphql",
    ".tf",
}
TEXT_NAMES = {
    "dockerfile",
    "makefile",
    "procfile",
    "rakefile",
    "gemfile",
    "justfile",
    "cmakelists.txt",
}

SKIP_DIRS = {
    "node_modules",
    ".git",
    ".hg",
    ".svn",
    "venv",
    ".venv",
    "env",
    ".env",
    "__pycache__",
    "dist",
    "build",
    ".next",
    ".nuxt",
    "target",
    "vendor",
    ".tox",
    ".nox",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "coverage",
    ".coverage",
    "htmlcov",
    ".idea",
    ".vscode",
    "site-packages",
    "bower_components",
    ".cache",
    ".gradle",
    "pods",
    "deriveddata",
    ".terraform",
    ".serverless",
    "bin",
    "obj",
    ".dart_tool",
    ".parcel-cache",
    ".turbo",
    ".output",
    "__snapshots__",
}
LOCK_FILES = {
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "bun.lockb",
    "bun.lock",
    "poetry.lock",
    "uv.lock",
    "pipfile.lock",
    "cargo.lock",
    "gemfile.lock",
    "composer.lock",
    "go.sum",
    "packages.lock.json",
    "pubspec.lock",
    "flake.lock",
}
BINARY_EXTS = {
    ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".ico", ".webp", ".svg", ".tif", ".tiff", ".psd",
    ".mp3", ".mp4", ".wav", ".ogg", ".mov", ".avi", ".mkv", ".flac", ".webm",
    ".woff", ".woff2", ".ttf", ".otf", ".eot",
    ".zip", ".gz", ".tar", ".tgz", ".bz2", ".xz", ".7z", ".rar", ".jar", ".war", ".whl", ".egg",
    ".pdf", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx",
    ".exe", ".dll", ".so", ".dylib", ".o", ".a", ".class", ".pyc", ".pyo", ".pyd", ".wasm",
    ".db", ".sqlite", ".sqlite3", ".bin", ".dat", ".pkl", ".pickle", ".npy", ".npz", ".parquet",
    ".map", ".lock", ".ds_store", ".icns", ".model", ".onnx", ".pt", ".h5",
}  # fmt: skip
GENERATED_PATTERNS = [
    re.compile(r"\.min\.(js|css)$"),
    re.compile(r"\.pb\.go$"),
    re.compile(r"_pb2(_grpc)?\.py$"),
    re.compile(r"\.generated\.\w+$"),
    re.compile(r"\.g\.(dart|cs)$"),
    re.compile(r"\.d\.ts$"),
    re.compile(r"\.designer\.cs$", re.IGNORECASE),
    re.compile(r"(^|/)migrations?/\d{4,}.*\.(py|js|ts|sql)$"),
    re.compile(r"\.bundle\.js$"),
    re.compile(r"(^|/)(schema|prisma)\.generated"),
]
GENERATED_MARKERS = (
    b"@generated",
    b"do not edit",
    b"DO NOT EDIT",
    b"auto-generated",
    b"autogenerated",
)

SKIP_REASONS = frozenset(
    {
        "ignored_dir",
        "gitignore",
        "lock_file",
        "binary",
        "media",
        "generated",
        "minified",
        "too_large",
        "unreadable",
    }
)
SkipReason = Literal[
    "ignored_dir",
    "gitignore",
    "lock_file",
    "binary",
    "media",
    "generated",
    "minified",
    "too_large",
    "unreadable",
]


class ScannedFile(BaseModel):
    path: str
    language: Language
    size: int
    lines: int


class SkippedFile(BaseModel):
    path: str
    reason: SkipReason


class EntryHint(BaseModel):
    kind: str = Field(description="e.g. package_main, npm_script, dockerfile_cmd, pyproject_script")
    file: str
    detail: str


class LanguageStat(BaseModel):
    files: int = 0
    lines: int = 0


class ScanResult(BaseModel):
    root: str
    files: list[ScannedFile]
    skipped: list[SkippedFile]
    skipped_counts: dict[str, int]
    languages: dict[str, LanguageStat]
    frameworks: list[str]
    manifests: list[str]
    entry_hints: list[EntryHint]
    readme_excerpt: str
    tree: str

    @property
    def code_files(self) -> list[ScannedFile]:
        return [f for f in self.files if f.language != "text"]


@dataclass
class ScanLimits:
    max_file_bytes: int = 1_000_000
    max_files: int = 20_000
    max_skipped_listed: int = 300
    readme_chars: int = 1500
    tree_max_lines: int = 400


def detect_language(path: Path) -> Language | None:
    name = path.name.lower()
    ext = path.suffix.lower()
    if ext in EXT_LANGUAGE:
        return EXT_LANGUAGE[ext]
    if ext in TEXT_EXTS or name in TEXT_NAMES or name.startswith("dockerfile"):
        return "text"
    if ext == "" and name in TEXT_NAMES:
        return "text"
    return None


def _looks_binary(sample: bytes) -> bool:
    return b"\x00" in sample


def _looks_minified(sample: bytes) -> bool:
    lines = sample.split(b"\n")
    if len(lines) <= 1 and len(sample) > 2000:
        return True
    longest = max((len(line) for line in lines), default=0)
    return longest > 1500


def _looks_generated(rel: str, sample: bytes) -> bool:
    if any(p.search(rel) for p in GENERATED_PATTERNS):
        return True
    head = sample[:600]
    return any(marker in head for marker in GENERATED_MARKERS)


class _IgnoreStack:
    """Collects .gitignore files while walking so nested ignores apply to their subtree."""

    def __init__(self, root: Path) -> None:
        self.root = root
        self.specs: list[tuple[str, pathspec.GitIgnoreSpec]] = []
        self._load(root, "")

    def _load(self, directory: Path, prefix: str) -> None:
        gi = directory / ".gitignore"
        if gi.is_file():
            try:
                lines = gi.read_text(encoding="utf-8", errors="ignore").splitlines()
            except OSError:
                return
            self.specs.append((prefix, pathspec.GitIgnoreSpec.from_lines(lines)))

    def enter(self, directory: Path, prefix: str) -> None:
        self._load(directory, prefix)

    def ignored(self, rel: str, *, is_dir: bool) -> bool:
        probe = rel + "/" if is_dir else rel
        for prefix, spec in self.specs:
            if prefix and not rel.startswith(prefix):
                continue
            sub = probe[len(prefix) :] if prefix else probe
            if spec.match_file(sub):
                return True
        return False


def _walk(root: Path, ignores: _IgnoreStack) -> Iterator[tuple[Path, str, SkipReason | None]]:
    stack: list[tuple[Path, str]] = [(root, "")]
    while stack:
        directory, prefix = stack.pop()
        try:
            children = sorted(directory.iterdir(), key=lambda p: p.name.lower())
        except OSError:
            continue
        for child in children:
            rel = f"{prefix}{child.name}"
            if child.is_symlink():
                continue
            if child.is_dir():
                if child.name.lower() in SKIP_DIRS:
                    yield child, rel, "ignored_dir"
                    continue
                if ignores.ignored(rel, is_dir=True):
                    yield child, rel, "gitignore"
                    continue
                ignores.enter(child, rel + "/")
                stack.append((child, rel + "/"))
            elif child.is_file():
                yield child, rel, None


MEDIA_EXTS = {".png", ".jpg", ".jpeg", ".gif", ".svg", ".mp3", ".mp4", ".webp", ".ico"}


def _classify_by_name(path: Path) -> Language | SkipReason:
    name = path.name.lower()
    if name in LOCK_FILES:
        return "lock_file"
    ext = path.suffix.lower()
    if ext in BINARY_EXTS:
        return "media" if ext in MEDIA_EXTS else "binary"
    language = detect_language(path)
    return language if language is not None else "binary"


def _sniff(path: Path, rel: str, language: Language, limits: ScanLimits) -> SkipReason | None:
    if path.stat().st_size > limits.max_file_bytes:
        return "too_large"
    with path.open("rb") as fh:
        sample = fh.read(8192)
    if _looks_binary(sample):
        return "binary"
    if language != "text" and _looks_generated(rel, sample):
        return "generated"
    if language != "text" and _looks_minified(sample):
        return "minified"
    return None


def _classify(path: Path, rel: str, limits: ScanLimits) -> tuple[Language, int, int] | SkipReason:
    verdict = _classify_by_name(path)
    if verdict in SKIP_REASONS:
        return verdict  # type: ignore[return-value]
    language: Language = verdict  # type: ignore[assignment]
    try:
        reason = _sniff(path, rel, language, limits)
        if reason is not None:
            return reason
        with path.open("rb") as fh:
            lines = sum(1 for _ in fh)
        return language, path.stat().st_size, lines
    except OSError:
        return "unreadable"


def _read_text(path: Path, limit: int = 200_000) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="ignore")[:limit]
    except OSError:
        return ""


FRAMEWORK_DEPS = {
    "express": "Express",
    "fastify": "Fastify",
    "koa": "Koa",
    "@nestjs/core": "NestJS",
    "next": "Next.js",
    "react": "React",
    "vue": "Vue",
    "svelte": "Svelte",
    "@angular/core": "Angular",
    "hono": "Hono",
    "prisma": "Prisma",
    "@prisma/client": "Prisma",
    "mongoose": "Mongoose",
    "sequelize": "Sequelize",
    "typeorm": "TypeORM",
    "knex": "Knex",
    "pg": "PostgreSQL client",
    "mysql2": "MySQL client",
    "sqlite3": "SQLite",
    "better-sqlite3": "SQLite",
    "redis": "Redis",
    "bullmq": "BullMQ",
    "flask": "Flask",
    "django": "Django",
    "fastapi": "FastAPI",
    "click": "Click CLI",
    "typer": "Typer CLI",
    "sqlalchemy": "SQLAlchemy",
    "celery": "Celery",
    "pandas": "pandas",
    "streamlit": "Streamlit",
    "aiohttp": "aiohttp",
    "tornado": "Tornado",
    "pydantic": "Pydantic",
}
GO_FRAMEWORKS = {
    "gin-gonic/gin": "Gin",
    "labstack/echo": "Echo",
    "go-chi/chi": "Chi",
    "gofiber/fiber": "Fiber",
    "gorilla/mux": "Gorilla Mux",
}
RUST_FRAMEWORKS = {
    "actix-web": "Actix Web",
    "axum": "Axum",
    "rocket": "Rocket",
    "clap": "Clap CLI",
    "tokio": "Tokio",
}
RUBY_FRAMEWORKS = {"rails": "Rails", "sinatra": "Sinatra", "sidekiq": "Sidekiq"}
PHP_FRAMEWORKS = {"laravel/framework": "Laravel", "symfony/symfony": "Symfony", "slim/slim": "Slim"}
JAVA_MARKERS = {
    "spring-boot": "Spring Boot",
    "quarkus": "Quarkus",
    "micronaut": "Micronaut",
    "jakarta.ws.rs": "JAX-RS",
}


def _find(by_name: dict[str, str], name: str) -> list[str]:
    return [p for lower, p in by_name.items() if lower == name or lower.endswith("/" + name)]


def _package_json(root: Path, rel: str, frameworks: set[str], hints: list[EntryHint]) -> None:
    try:
        data = json.loads(_read_text(root / rel))
    except json.JSONDecodeError:
        return
    if not isinstance(data, dict):
        return
    deps = {**data.get("dependencies", {}), **data.get("devDependencies", {})}
    frameworks.update(v for k, v in FRAMEWORK_DEPS.items() if k in deps)
    if isinstance(data.get("main"), str):
        hints.append(EntryHint(kind="package_main", file=rel, detail=data["main"]))
    bins = data.get("bin")
    if isinstance(bins, str):
        hints.append(EntryHint(kind="package_bin", file=rel, detail=bins))
    elif isinstance(bins, dict):
        hints.extend(
            EntryHint(kind="package_bin", file=rel, detail=f"{k}: {v}") for k, v in bins.items()
        )
    scripts = data.get("scripts", {})
    for key in ("start", "dev", "serve", "build"):
        if key in scripts:
            hints.append(EntryHint(kind="npm_script", file=rel, detail=f"{key}: {scripts[key]}"))


def _pyproject(root: Path, rel: str, frameworks: set[str], hints: list[EntryHint]) -> None:
    try:
        data = tomllib.loads(_read_text(root / rel))
    except tomllib.TOMLDecodeError:
        return
    project = data.get("project", {})
    poetry = data.get("tool", {}).get("poetry", {}).get("dependencies", {})
    dep_text = " ".join(project.get("dependencies", [])).lower() + " " + " ".join(poetry).lower()
    frameworks.update(
        v for k, v in FRAMEWORK_DEPS.items() if re.search(rf"\b{re.escape(k)}\b", dep_text)
    )
    for name, target in project.get("scripts", {}).items():
        hints.append(EntryHint(kind="pyproject_script", file=rel, detail=f"{name} = {target}"))


def _requirements(root: Path, rel: str, frameworks: set[str], _hints: list[EntryHint]) -> None:
    text = _read_text(root / rel).lower()
    frameworks.update(
        v for k, v in FRAMEWORK_DEPS.items() if re.search(rf"^{re.escape(k)}\b", text, re.M)
    )


def _substring_detector(
    table: dict[str, str], *, quoted: bool = False
) -> Callable[[Path, str, set[str], list[EntryHint]], None]:
    def detect(root: Path, rel: str, frameworks: set[str], _hints: list[EntryHint]) -> None:
        text = _read_text(root / rel)
        for key, label in table.items():
            needles = (f"'{key}'", f'"{key}"') if quoted else (key,)
            if any(n in text for n in needles):
                frameworks.add(label)

    return detect


def _dockerfile(root: Path, rel: str, _frameworks: set[str], hints: list[EntryHint]) -> None:
    for line in _read_text(root / rel).splitlines():
        stripped = line.strip()
        if stripped.upper().startswith(("CMD", "ENTRYPOINT")):
            hints.append(EntryHint(kind="dockerfile_cmd", file=rel, detail=stripped[:200]))


def _procfile(root: Path, rel: str, _frameworks: set[str], hints: list[EntryHint]) -> None:
    for line in _read_text(root / rel).splitlines():
        if ":" in line:
            hints.append(EntryHint(kind="procfile", file=rel, detail=line.strip()[:200]))


def _csproj(root: Path, rel: str, frameworks: set[str], _hints: list[EntryHint]) -> None:
    text = _read_text(root / rel)
    if "Microsoft.AspNetCore" in text or 'Sdk="Microsoft.NET.Sdk.Web"' in text:
        frameworks.add("ASP.NET Core")


MANIFEST_HANDLERS: list[tuple[str, Callable[[Path, str, set[str], list[EntryHint]], None]]] = [
    ("package.json", _package_json),
    ("requirements.txt", _requirements),
    ("pyproject.toml", _pyproject),
    ("go.mod", _substring_detector(GO_FRAMEWORKS)),
    ("cargo.toml", _substring_detector(RUST_FRAMEWORKS)),
    ("gemfile", _substring_detector(RUBY_FRAMEWORKS, quoted=True)),
    ("composer.json", _substring_detector(PHP_FRAMEWORKS)),
    ("pom.xml", _substring_detector(JAVA_MARKERS)),
    ("build.gradle", _substring_detector(JAVA_MARKERS)),
    ("build.gradle.kts", _substring_detector(JAVA_MARKERS)),
    ("procfile", _procfile),
]


def _manifest_info(
    root: Path, files: list[ScannedFile]
) -> tuple[list[str], list[str], list[EntryHint]]:
    frameworks: set[str] = set()
    manifests: list[str] = []
    hints: list[EntryHint] = []
    by_name = {f.path.lower(): f.path for f in files}
    for name, handler in MANIFEST_HANDLERS:
        for rel in _find(by_name, name):
            manifests.append(rel)
            handler(root, rel, frameworks, hints)
    for rel in [p for lower, p in by_name.items() if lower.endswith(".csproj")]:
        manifests.append(rel)
        _csproj(root, rel, frameworks, hints)
    dockerfiles = [
        p for lower, p in by_name.items() if lower.rsplit("/", 1)[-1].startswith("dockerfile")
    ]
    for rel in dockerfiles:
        manifests.append(rel)
        _dockerfile(root, rel, frameworks, hints)
    return sorted(frameworks), sorted(set(manifests)), hints


def _readme_excerpt(root: Path, files: list[ScannedFile], chars: int) -> str:
    candidates = [f.path for f in files if f.path.lower().rsplit("/", 1)[-1].startswith("readme")]
    candidates.sort(key=lambda p: (p.count("/"), len(p)))
    if not candidates:
        return ""
    text = _read_text(root / candidates[0], limit=chars * 4)
    text = re.sub(r"!\[[^\]]*\]\([^)]*\)", "", text)  # drop images
    text = re.sub(r"<[^>]+>", "", text)  # drop html
    text = re.sub(r"\n{3,}", "\n\n", text).strip()
    return text[:chars]


def build_tree(paths: list[str], max_lines: int) -> str:
    """Compact indented tree; directories with many files are elided."""
    tree: dict[str, dict] = {}  # type: ignore[type-arg]
    for p in paths:
        node = tree
        for part in p.split("/"):
            node = node.setdefault(part, {})
    lines: list[str] = []

    def emit(node: dict, depth: int) -> None:  # type: ignore[type-arg]
        dirs = sorted(k for k, v in node.items() if v)
        files = sorted(k for k, v in node.items() if not v)
        for d in dirs:
            if len(lines) >= max_lines:
                return
            lines.append("  " * depth + d + "/")
            emit(node[d], depth + 1)
        shown = files if len(files) <= 12 else files[:10]
        for f in shown:
            if len(lines) >= max_lines:
                return
            lines.append("  " * depth + f)
        if len(files) > len(shown):
            lines.append("  " * depth + f"… {len(files) - len(shown)} more files")

    emit(tree, 0)
    if len(lines) >= max_lines:
        lines.append("… (tree truncated)")
    return "\n".join(lines)


def scan_project(root: Path, limits: ScanLimits | None = None) -> ScanResult:
    limits = limits or ScanLimits()
    ignores = _IgnoreStack(root)
    files: list[ScannedFile] = []
    skipped: list[SkippedFile] = []
    counts: Counter[str] = Counter()

    def skip(rel: str, reason: SkipReason) -> None:
        counts[reason] += 1
        if len(skipped) < limits.max_skipped_listed:
            skipped.append(SkippedFile(path=rel, reason=reason))

    for path, rel, dir_reason in _walk(root, ignores):
        if dir_reason is not None:
            skip(rel + "/", dir_reason)
            continue
        if ignores.ignored(rel, is_dir=False):
            skip(rel, "gitignore")
            continue
        result = _classify(path, rel, limits)
        if isinstance(result, str):
            skip(rel, result)
            continue
        language, size, lines = result
        files.append(ScannedFile(path=rel, language=language, size=size, lines=lines))
        if len(files) >= limits.max_files:
            break

    stats: dict[str, LanguageStat] = {}
    for f in files:
        st = stats.setdefault(f.language, LanguageStat())
        st.files += 1
        st.lines += f.lines
    frameworks, manifests, hints = _manifest_info(root, files)
    return ScanResult(
        root=str(root),
        files=files,
        skipped=skipped,
        skipped_counts=dict(counts),
        languages=stats,
        frameworks=frameworks,
        manifests=manifests,
        entry_hints=hints,
        readme_excerpt=_readme_excerpt(root, files, limits.readme_chars),
        tree=build_tree([f.path for f in files], limits.tree_max_lines),
    )
